# Generated by Django 3.2.8 on 2021-10-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
