# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# https://dev.to/n3wt0n/container-image-promotion-across-environments-yaml-1ca6

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.SourceVersion)'
  ImageName: 'example-backend-profile'
  azureSubscription: HKI-kanslia-standalone
  appName: example-backend-profile
  containerRegistry: registry.hub.docker.com

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build the images
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - script: |
          echo 'Running in workspace $(Pipeline.Workspace)'
          echo 'Build.SourceVersion: $(Build.SourceVersion)'
          echo 'Build.SourceVersionMessage: $(Build.SourceVersionMessage)'
          echo 'Build.SourcesDirectory: $(Build.SourcesDirectory)'
          echo 'Build.ArtifactStagingDirectory: $(build.artifactstagingdirectory)'
    - task: DockerCompose@0
      displayName: Build images
      inputs:
        dockerComposeCommand: build
        dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
        includeSourceTags: true
        includeLatestTag: true
    - task: Docker@2
      displayName: Build APM enhanced image
      inputs:
        repository: '$(ImageName)'
        command: build
        tags: 'apm'
        Dockerfile: deploy/elastic_apm_injection/Dockerfile
        arguments: --build-arg BASE_IMAGE=$(ImageName)
    - script: |
        docker tag example-backend_dev:latest example-backend:dev_latest
        docker rmi example-backend_dev
      displayName:
    - task: Docker@2
      displayName: Save example-backend image repository to TAR
      inputs:
        repository: '$(ImageName)'
        command: save
        arguments: '--output $(build.artifactstagingdirectory)/$(ImageName).image.tar $(ImageName)'
        addPipelineData: false
    - publish: $(build.artifactstagingdirectory)
      artifact: ContainerImages
- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test the dev image
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download example-backend repository TAR
        inputs:
          artifact: ContainerImages
      - task: Docker@2
        displayName: Load example-backend repository from TAR
        inputs:
          command: load
          arguments: '--input $(Pipeline.Workspace)/$(ImageName).image.tar'
      - script: |
          docker tag example-backend:dev_latest example-backend_dev:latest
        displayName: Add example-backend_dev name back to image for docker-compose
      - task: DockerCompose@0
        displayName: Run tests
        inputs:
          dockerComposeCommand: run dev test
          dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
- stage: Push
  displayName: Push
  jobs:
  - job: Push
    displayName: Push deploy image to registry
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download image repo TAR
        inputs:
          artifact: ContainerImages
      - task: Docker@2
        displayName: Load image repository from TAR
        inputs:
          command: load
          arguments: '--input $(Pipeline.Workspace)/$(ImageName).image.tar'
      - script: |
          docker tag $(ImageName):latest helsinki/$(ImageName):latest
          docker tag $(ImageName):latest helsinki/$(ImageName):$(tag)
          docker tag $(ImageName):apm helsinki/$(ImageName):latest_apm
          docker tag $(ImageName):apm helsinki/$(ImageName):$(tag)_apm
        displayName: Do image retagging for helsinki repo
      - task: Docker@2
        displayName: Push image to Docker hub
        inputs:
          containerRegistry: Docker hub upload-example-backend-profile
          repository: helsinki/$(ImageName)
          command: push
          tags: |
            latest
            $(tag)
            latest_apm
            $(tag)_apm
- stage: Deploy
  displayName: Deploy to Openshift
  jobs:
  - job: Update
    displayName: Update OC Imagestream
    steps:
      - task: oc-cmd@2
        displayName: Add OC tag to latest image
        inputs:
          openshiftService: 'Azure OpenShift'
          cmd: 'tag docker.io/helsinki/example-backend:$(tag) example-backend-backend:latest'
