services:
  django:
    container_name: example-backend-profile
    build: .
    ports:
      - 127.0.0.1:8081:8000
    env_file: config.env

    volumes:
      - .:/opt/app-root/src:cached

networks:
  default:
    name: helsinki
